### ISSUE TITLE
latest push errors out

### ISSUE THREAD

**Issue by chrismccoy** [wolffe/hound#12]
Notice: Undefined variable: listofpage in /Users/chris/Sites/hound/libs/hound.php on line 123

    Warning: in_array() expects parameter 2 to be array, null given in /Users/chris/Sites/hound/libs/hound.php on line 123

    Warning: file_get_contents(site/pages/page-index.txt): failed to open stream: No such file or directory in /Users/chris/Sites/hound/libs/hound.php on line 241

    Warning: array_multisort(): Argument #1 is expected to be an array or a sort flag in /Users/chris/Sites/hound/libs/hound.php on line 130

    Warning: Invalid argument supplied for foreach() in /Users/chris/Sites/hound/libs/hound.php on line 132

this is from a basic git clone of the repo

**Comment by wolffe** [comment]
Thanks, that's because of the default theme. Will fix it in the next release.

**Comment by wolffe** [comment]
Added a welcome screen for fresh installations or for no index page found.

![9e6ea2e987246e9fc3924ad811e156b4](https://cloud.githubusercontent.com/assets/910240/23944284/2b8274d6-096a-11e7-8543-a3c7abc611cf.png)
